# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/adjdeclentry.ui'
#
# Created: Thu Jan 25 11:35:25 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdjDeclEntry(object):
    def setupUi(self, AdjDeclEntry):
        AdjDeclEntry.setObjectName("AdjDeclEntry")
        AdjDeclEntry.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/machinetrans/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdjDeclEntry.setWindowIcon(icon)
        self.titleLbl = QtWidgets.QLabel(AdjDeclEntry)
        self.titleLbl.setGeometry(QtCore.QRect(10, 30, 780, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.nomEdit = LineEditRU(AdjDeclEntry)
        self.nomEdit.setGeometry(QtCore.QRect(30, 380, 340, 30))
        self.nomEdit.setObjectName("nomEdit")
        self.nomLbl = QtWidgets.QLabel(AdjDeclEntry)
        self.nomLbl.setGeometry(QtCore.QRect(30, 350, 340, 25))
        self.nomLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.nomLbl.setObjectName("nomLbl")
        self.genLbl = QtWidgets.QLabel(AdjDeclEntry)
        self.genLbl.setGeometry(QtCore.QRect(30, 410, 340, 25))
        self.genLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.genLbl.setObjectName("genLbl")
        self.genEdit = LineEditRU(AdjDeclEntry)
        self.genEdit.setGeometry(QtCore.QRect(30, 440, 340, 30))
        self.genEdit.setObjectName("genEdit")
        self.insLbl = QtWidgets.QLabel(AdjDeclEntry)
        self.insLbl.setGeometry(QtCore.QRect(30, 470, 340, 25))
        self.insLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.insLbl.setObjectName("insLbl")
        self.insEdit = LineEditRU(AdjDeclEntry)
        self.insEdit.setGeometry(QtCore.QRect(30, 500, 340, 30))
        self.insEdit.setObjectName("insEdit")
        self.accLbl = QtWidgets.QLabel(AdjDeclEntry)
        self.accLbl.setGeometry(QtCore.QRect(430, 350, 340, 25))
        self.accLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.accLbl.setObjectName("accLbl")
        self.accEdit = LineEditRU(AdjDeclEntry)
        self.accEdit.setGeometry(QtCore.QRect(430, 380, 340, 30))
        self.accEdit.setObjectName("accEdit")
        self.datLbl = QtWidgets.QLabel(AdjDeclEntry)
        self.datLbl.setGeometry(QtCore.QRect(430, 410, 340, 25))
        self.datLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.datLbl.setObjectName("datLbl")
        self.datEdit = LineEditRU(AdjDeclEntry)
        self.datEdit.setGeometry(QtCore.QRect(430, 440, 340, 30))
        self.datEdit.setObjectName("datEdit")
        self.prpLbl = QtWidgets.QLabel(AdjDeclEntry)
        self.prpLbl.setGeometry(QtCore.QRect(430, 470, 340, 25))
        self.prpLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.prpLbl.setObjectName("prpLbl")
        self.prpEdit = LineEditRU(AdjDeclEntry)
        self.prpEdit.setGeometry(QtCore.QRect(430, 500, 340, 30))
        self.prpEdit.setObjectName("prpEdit")
        self.rejectBttn = QtWidgets.QPushButton(AdjDeclEntry)
        self.rejectBttn.setGeometry(QtCore.QRect(30, 530, 150, 50))
        self.rejectBttn.setObjectName("rejectBttn")
        self.acceptBttn = QtWidgets.QPushButton(AdjDeclEntry)
        self.acceptBttn.setGeometry(QtCore.QRect(620, 530, 150, 50))
        self.acceptBttn.setObjectName("acceptBttn")
        self.tableView = QtWidgets.QTextBrowser(AdjDeclEntry)
        self.tableView.setGeometry(QtCore.QRect(10, 70, 780, 180))
        self.tableView.setObjectName("tableView")
        self.gender = QtWidgets.QGroupBox(AdjDeclEntry)
        self.gender.setGeometry(QtCore.QRect(10, 260, 770, 50))
        self.gender.setTitle("")
        self.gender.setFlat(True)
        self.gender.setObjectName("gender")
        self.anim = QtWidgets.QRadioButton(self.gender)
        self.anim.setGeometry(QtCore.QRect(20, 0, 120, 25))
        self.anim.setChecked(True)
        self.anim.setObjectName("anim")
        self.inan = QtWidgets.QRadioButton(self.gender)
        self.inan.setGeometry(QtCore.QRect(230, 0, 140, 25))
        self.inan.setObjectName("inan")
        self.fem = QtWidgets.QRadioButton(self.gender)
        self.fem.setGeometry(QtCore.QRect(450, 0, 130, 25))
        self.fem.setObjectName("fem")
        self.nuet = QtWidgets.QRadioButton(self.gender)
        self.nuet.setGeometry(QtCore.QRect(640, 0, 120, 25))
        self.nuet.setObjectName("nuet")
        self.pluranim = QtWidgets.QRadioButton(self.gender)
        self.pluranim.setGeometry(QtCore.QRect(170, 30, 190, 25))
        self.pluranim.setObjectName("pluranim")
        self.plurinan = QtWidgets.QRadioButton(self.gender)
        self.plurinan.setGeometry(QtCore.QRect(450, 30, 210, 25))
        self.plurinan.setObjectName("plurinan")
        self.helpBttn = QtWidgets.QPushButton(AdjDeclEntry)
        self.helpBttn.setGeometry(QtCore.QRect(640, 10, 150, 50))
        self.helpBttn.setObjectName("helpBttn")
        self.stemEdit = LineEditRU(AdjDeclEntry)
        self.stemEdit.setGeometry(QtCore.QRect(510, 320, 260, 30))
        self.stemEdit.setObjectName("stemEdit")
        self.stemLbl = QtWidgets.QLabel(AdjDeclEntry)
        self.stemLbl.setGeometry(QtCore.QRect(420, 320, 70, 25))
        self.stemLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stemLbl.setObjectName("stemLbl")
        self.engLbl = QtWidgets.QLabel(AdjDeclEntry)
        self.engLbl.setGeometry(QtCore.QRect(30, 320, 80, 25))
        self.engLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.engLbl.setObjectName("engLbl")
        self.engEdit = LineEditEN(AdjDeclEntry)
        self.engEdit.setGeometry(QtCore.QRect(120, 320, 240, 30))
        self.engEdit.setText("")
        self.engEdit.setObjectName("engEdit")
        self.declBttn = QtWidgets.QPushButton(AdjDeclEntry)
        self.declBttn.setGeometry(QtCore.QRect(325, 530, 150, 50))
        self.declBttn.setObjectName("declBttn")

        self.retranslateUi(AdjDeclEntry)
        QtCore.QMetaObject.connectSlotsByName(AdjDeclEntry)
        AdjDeclEntry.setTabOrder(self.helpBttn, self.tableView)
        AdjDeclEntry.setTabOrder(self.tableView, self.anim)
        AdjDeclEntry.setTabOrder(self.anim, self.inan)
        AdjDeclEntry.setTabOrder(self.inan, self.fem)
        AdjDeclEntry.setTabOrder(self.fem, self.nuet)
        AdjDeclEntry.setTabOrder(self.nuet, self.pluranim)
        AdjDeclEntry.setTabOrder(self.pluranim, self.plurinan)
        AdjDeclEntry.setTabOrder(self.plurinan, self.engEdit)
        AdjDeclEntry.setTabOrder(self.engEdit, self.stemEdit)
        AdjDeclEntry.setTabOrder(self.stemEdit, self.nomEdit)
        AdjDeclEntry.setTabOrder(self.nomEdit, self.accEdit)
        AdjDeclEntry.setTabOrder(self.accEdit, self.genEdit)
        AdjDeclEntry.setTabOrder(self.genEdit, self.datEdit)
        AdjDeclEntry.setTabOrder(self.datEdit, self.insEdit)
        AdjDeclEntry.setTabOrder(self.insEdit, self.prpEdit)
        AdjDeclEntry.setTabOrder(self.prpEdit, self.rejectBttn)
        AdjDeclEntry.setTabOrder(self.rejectBttn, self.declBttn)
        AdjDeclEntry.setTabOrder(self.declBttn, self.acceptBttn)

    def retranslateUi(self, AdjDeclEntry):
        _translate = QtCore.QCoreApplication.translate
        AdjDeclEntry.setWindowTitle(_translate("AdjDeclEntry", "Russian Adjectival Declension Entry"))
        self.titleLbl.setText(_translate("AdjDeclEntry", "Russian Adjectival Declension"))
        self.nomLbl.setText(_translate("AdjDeclEntry", "Nominative"))
        self.genLbl.setText(_translate("AdjDeclEntry", "Genitive"))
        self.insLbl.setText(_translate("AdjDeclEntry", "Instrumental"))
        self.accLbl.setText(_translate("AdjDeclEntry", "Accusative"))
        self.datLbl.setText(_translate("AdjDeclEntry", "Dative"))
        self.prpLbl.setText(_translate("AdjDeclEntry", "Prepositional"))
        self.rejectBttn.setText(_translate("AdjDeclEntry", "Reject"))
        self.acceptBttn.setText(_translate("AdjDeclEntry", "Accept"))
        self.anim.setText(_translate("AdjDeclEntry", "Animate"))
        self.inan.setText(_translate("AdjDeclEntry", "Inanimate"))
        self.fem.setText(_translate("AdjDeclEntry", "Feminine"))
        self.nuet.setText(_translate("AdjDeclEntry", "Nueter"))
        self.pluranim.setText(_translate("AdjDeclEntry", "Plural Animate"))
        self.plurinan.setText(_translate("AdjDeclEntry", "Plural Inanimate"))
        self.helpBttn.setText(_translate("AdjDeclEntry", "Help"))
        self.stemLbl.setText(_translate("AdjDeclEntry", "Stem"))
        self.engLbl.setText(_translate("AdjDeclEntry", "English"))
        self.declBttn.setText(_translate("AdjDeclEntry", "Declensions"))

from machinetrans.lineediten import LineEditEN
from machinetrans.lineeditru import LineEditRU
