# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/declentry.ui'
#
# Created: Thu Jan 25 11:35:25 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DeclEntry(object):
    def setupUi(self, DeclEntry):
        DeclEntry.setObjectName("DeclEntry")
        DeclEntry.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/machinetrans/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DeclEntry.setWindowIcon(icon)
        self.titleLbl = QtWidgets.QLabel(DeclEntry)
        self.titleLbl.setGeometry(QtCore.QRect(10, 20, 780, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.nomEdit = LineEditRU(DeclEntry)
        self.nomEdit.setGeometry(QtCore.QRect(30, 350, 340, 30))
        self.nomEdit.setObjectName("nomEdit")
        self.nomLbl = QtWidgets.QLabel(DeclEntry)
        self.nomLbl.setGeometry(QtCore.QRect(30, 320, 340, 25))
        self.nomLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.nomLbl.setObjectName("nomLbl")
        self.genLbl = QtWidgets.QLabel(DeclEntry)
        self.genLbl.setGeometry(QtCore.QRect(30, 390, 340, 25))
        self.genLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.genLbl.setObjectName("genLbl")
        self.genEdit = LineEditRU(DeclEntry)
        self.genEdit.setGeometry(QtCore.QRect(30, 420, 340, 30))
        self.genEdit.setObjectName("genEdit")
        self.insLbl = QtWidgets.QLabel(DeclEntry)
        self.insLbl.setGeometry(QtCore.QRect(30, 460, 340, 25))
        self.insLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.insLbl.setObjectName("insLbl")
        self.insEdit = LineEditRU(DeclEntry)
        self.insEdit.setGeometry(QtCore.QRect(30, 490, 340, 30))
        self.insEdit.setObjectName("insEdit")
        self.accLbl = QtWidgets.QLabel(DeclEntry)
        self.accLbl.setGeometry(QtCore.QRect(430, 320, 340, 25))
        self.accLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.accLbl.setObjectName("accLbl")
        self.accEdit = LineEditRU(DeclEntry)
        self.accEdit.setGeometry(QtCore.QRect(430, 350, 340, 30))
        self.accEdit.setObjectName("accEdit")
        self.datLbl = QtWidgets.QLabel(DeclEntry)
        self.datLbl.setGeometry(QtCore.QRect(430, 390, 340, 25))
        self.datLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.datLbl.setObjectName("datLbl")
        self.datEdit = LineEditRU(DeclEntry)
        self.datEdit.setGeometry(QtCore.QRect(430, 420, 340, 30))
        self.datEdit.setObjectName("datEdit")
        self.prpLbl = QtWidgets.QLabel(DeclEntry)
        self.prpLbl.setGeometry(QtCore.QRect(430, 460, 340, 25))
        self.prpLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.prpLbl.setObjectName("prpLbl")
        self.prpEdit = LineEditRU(DeclEntry)
        self.prpEdit.setGeometry(QtCore.QRect(430, 490, 340, 30))
        self.prpEdit.setObjectName("prpEdit")
        self.rejectBttn = QtWidgets.QPushButton(DeclEntry)
        self.rejectBttn.setGeometry(QtCore.QRect(130, 530, 150, 50))
        self.rejectBttn.setObjectName("rejectBttn")
        self.acceptBttn = QtWidgets.QPushButton(DeclEntry)
        self.acceptBttn.setGeometry(QtCore.QRect(550, 530, 150, 50))
        self.acceptBttn.setObjectName("acceptBttn")
        self.tableView = QtWidgets.QTextBrowser(DeclEntry)
        self.tableView.setGeometry(QtCore.QRect(10, 60, 780, 180))
        self.tableView.setObjectName("tableView")
        self.stemEdit = LineEditRU(DeclEntry)
        self.stemEdit.setGeometry(QtCore.QRect(430, 280, 340, 30))
        self.stemEdit.setObjectName("stemEdit")
        self.stemLbl = QtWidgets.QLabel(DeclEntry)
        self.stemLbl.setGeometry(QtCore.QRect(430, 250, 340, 25))
        self.stemLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.stemLbl.setObjectName("stemLbl")
        self.engLbl = QtWidgets.QLabel(DeclEntry)
        self.engLbl.setGeometry(QtCore.QRect(30, 250, 340, 25))
        self.engLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.engLbl.setObjectName("engLbl")
        self.helpBttn = QtWidgets.QPushButton(DeclEntry)
        self.helpBttn.setGeometry(QtCore.QRect(640, 10, 150, 50))
        self.helpBttn.setObjectName("helpBttn")
        self.enEdit = LineEditEN(DeclEntry)
        self.enEdit.setGeometry(QtCore.QRect(30, 280, 340, 30))
        self.enEdit.setObjectName("enEdit")
        self.declBttn = QtWidgets.QPushButton(DeclEntry)
        self.declBttn.setGeometry(QtCore.QRect(330, 530, 150, 50))
        self.declBttn.setObjectName("declBttn")

        self.retranslateUi(DeclEntry)
        QtCore.QMetaObject.connectSlotsByName(DeclEntry)
        DeclEntry.setTabOrder(self.helpBttn, self.tableView)
        DeclEntry.setTabOrder(self.tableView, self.enEdit)
        DeclEntry.setTabOrder(self.enEdit, self.stemEdit)
        DeclEntry.setTabOrder(self.stemEdit, self.nomEdit)
        DeclEntry.setTabOrder(self.nomEdit, self.accEdit)
        DeclEntry.setTabOrder(self.accEdit, self.genEdit)
        DeclEntry.setTabOrder(self.genEdit, self.datEdit)
        DeclEntry.setTabOrder(self.datEdit, self.insEdit)
        DeclEntry.setTabOrder(self.insEdit, self.prpEdit)
        DeclEntry.setTabOrder(self.prpEdit, self.rejectBttn)
        DeclEntry.setTabOrder(self.rejectBttn, self.acceptBttn)

    def retranslateUi(self, DeclEntry):
        _translate = QtCore.QCoreApplication.translate
        DeclEntry.setWindowTitle(_translate("DeclEntry", "Russian Noun Declension Entry"))
        self.titleLbl.setText(_translate("DeclEntry", "Russian Noun Declension"))
        self.nomLbl.setText(_translate("DeclEntry", "Nominative"))
        self.genLbl.setText(_translate("DeclEntry", "Genitive"))
        self.insLbl.setText(_translate("DeclEntry", "Instrumental"))
        self.accLbl.setText(_translate("DeclEntry", "Accusative"))
        self.datLbl.setText(_translate("DeclEntry", "Dative"))
        self.prpLbl.setText(_translate("DeclEntry", "Prepositional"))
        self.rejectBttn.setText(_translate("DeclEntry", "Reject"))
        self.acceptBttn.setText(_translate("DeclEntry", "Accept"))
        self.stemLbl.setText(_translate("DeclEntry", "Noun Stem"))
        self.engLbl.setText(_translate("DeclEntry", "English"))
        self.helpBttn.setText(_translate("DeclEntry", "Help"))
        self.declBttn.setText(_translate("DeclEntry", "Declensions"))

from machinetrans.lineeditru import LineEditRU
from machinetrans.lineediten import LineEditEN
