# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/invarlist.ui'
#
# Created: Thu Jan 25 11:35:27 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InvarList(object):
    def setupUi(self, InvarList):
        InvarList.setObjectName("InvarList")
        InvarList.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(16)
        InvarList.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/machinetrans/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InvarList.setWindowIcon(icon)
        self.titleLbl = QtWidgets.QLabel(InvarList)
        self.titleLbl.setGeometry(QtCore.QRect(10, 20, 780, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.itemList = QtWidgets.QListWidget(InvarList)
        self.itemList.setGeometry(QtCore.QRect(10, 60, 780, 270))
        self.itemList.setObjectName("itemList")
        self.ruEdit = LineEditRU(InvarList)
        self.ruEdit.setGeometry(QtCore.QRect(430, 390, 330, 30))
        self.ruEdit.setObjectName("ruEdit")
        self.engLbl = QtWidgets.QLabel(InvarList)
        self.engLbl.setGeometry(QtCore.QRect(30, 350, 330, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.engLbl.setFont(font)
        self.engLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.engLbl.setObjectName("engLbl")
        self.ruLbl = QtWidgets.QLabel(InvarList)
        self.ruLbl.setGeometry(QtCore.QRect(440, 350, 330, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ruLbl.setFont(font)
        self.ruLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ruLbl.setObjectName("ruLbl")
        self.typeLbl = QtWidgets.QLabel(InvarList)
        self.typeLbl.setGeometry(QtCore.QRect(40, 440, 330, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.typeLbl.setFont(font)
        self.typeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.typeLbl.setObjectName("typeLbl")
        self.typeBox = QtWidgets.QComboBox(InvarList)
        self.typeBox.setGeometry(QtCore.QRect(40, 480, 330, 35))
        self.typeBox.setObjectName("typeBox")
        self.findBttn = QtWidgets.QPushButton(InvarList)
        self.findBttn.setGeometry(QtCore.QRect(190, 530, 110, 50))
        self.findBttn.setObjectName("findBttn")
        self.deleteBttn = QtWidgets.QPushButton(InvarList)
        self.deleteBttn.setGeometry(QtCore.QRect(340, 530, 110, 50))
        self.deleteBttn.setObjectName("deleteBttn")
        self.quitBttn = QtWidgets.QPushButton(InvarList)
        self.quitBttn.setGeometry(QtCore.QRect(40, 530, 110, 50))
        self.quitBttn.setObjectName("quitBttn")
        self.helpBttn = QtWidgets.QPushButton(InvarList)
        self.helpBttn.setGeometry(QtCore.QRect(640, 10, 150, 50))
        self.helpBttn.setObjectName("helpBttn")
        self.enEdit = LineEditEN(InvarList)
        self.enEdit.setGeometry(QtCore.QRect(40, 390, 330, 30))
        self.enEdit.setObjectName("enEdit")
        self.newBttn = QtWidgets.QPushButton(InvarList)
        self.newBttn.setGeometry(QtCore.QRect(500, 530, 110, 50))
        self.newBttn.setObjectName("newBttn")
        self.addBttn = QtWidgets.QPushButton(InvarList)
        self.addBttn.setGeometry(QtCore.QRect(650, 530, 110, 50))
        self.addBttn.setObjectName("addBttn")
        self.declLbl = QtWidgets.QLabel(InvarList)
        self.declLbl.setGeometry(QtCore.QRect(430, 440, 330, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.declLbl.setFont(font)
        self.declLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.declLbl.setObjectName("declLbl")
        self.declBox = QtWidgets.QComboBox(InvarList)
        self.declBox.setGeometry(QtCore.QRect(430, 480, 330, 35))
        self.declBox.setObjectName("declBox")

        self.retranslateUi(InvarList)
        QtCore.QMetaObject.connectSlotsByName(InvarList)
        InvarList.setTabOrder(self.helpBttn, self.itemList)
        InvarList.setTabOrder(self.itemList, self.enEdit)
        InvarList.setTabOrder(self.enEdit, self.ruEdit)
        InvarList.setTabOrder(self.ruEdit, self.typeBox)
        InvarList.setTabOrder(self.typeBox, self.declBox)
        InvarList.setTabOrder(self.declBox, self.quitBttn)
        InvarList.setTabOrder(self.quitBttn, self.findBttn)
        InvarList.setTabOrder(self.findBttn, self.deleteBttn)
        InvarList.setTabOrder(self.deleteBttn, self.newBttn)
        InvarList.setTabOrder(self.newBttn, self.addBttn)

    def retranslateUi(self, InvarList):
        _translate = QtCore.QCoreApplication.translate
        InvarList.setWindowTitle(_translate("InvarList", "Invariant List"))
        self.titleLbl.setText(_translate("InvarList", "Russian Invariant List"))
        self.engLbl.setText(_translate("InvarList", "English"))
        self.ruLbl.setText(_translate("InvarList", "Russian"))
        self.typeLbl.setText(_translate("InvarList", "Invariant Type"))
        self.findBttn.setText(_translate("InvarList", "Find"))
        self.deleteBttn.setText(_translate("InvarList", "Delete"))
        self.quitBttn.setText(_translate("InvarList", "Quit"))
        self.helpBttn.setText(_translate("InvarList", "Help"))
        self.newBttn.setText(_translate("InvarList", "New"))
        self.addBttn.setText(_translate("InvarList", "Add"))
        self.declLbl.setText(_translate("InvarList", "Takes Declension"))

from machinetrans.lineediten import LineEditEN
from machinetrans.lineeditru import LineEditRU
