# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/miscconj.ui'
#
# Created: Thu Jan 25 11:35:26 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MiscConj(object):
    def setupUi(self, MiscConj):
        MiscConj.setObjectName("MiscConj")
        MiscConj.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/machinetrans/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MiscConj.setWindowIcon(icon)
        self.enImpLbl = QtWidgets.QLabel(MiscConj)
        self.enImpLbl.setGeometry(QtCore.QRect(50, 430, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enImpLbl.setFont(font)
        self.enImpLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.enImpLbl.setObjectName("enImpLbl")
        self.femEdit = LineEditRU(MiscConj)
        self.femEdit.setGeometry(QtCore.QRect(420, 130, 330, 30))
        self.femEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.femEdit.setObjectName("femEdit")
        self.plurLbl = QtWidgets.QLabel(MiscConj)
        self.plurLbl.setGeometry(QtCore.QRect(420, 160, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plurLbl.setFont(font)
        self.plurLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.plurLbl.setObjectName("plurLbl")
        self.plurEdit = LineEditRU(MiscConj)
        self.plurEdit.setGeometry(QtCore.QRect(420, 180, 330, 30))
        self.plurEdit.setText("")
        self.plurEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.plurEdit.setObjectName("plurEdit")
        self.nuetEdit = LineEditRU(MiscConj)
        self.nuetEdit.setGeometry(QtCore.QRect(50, 180, 330, 30))
        self.nuetEdit.setText("")
        self.nuetEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.nuetEdit.setObjectName("nuetEdit")
        self.mascEdit = LineEditRU(MiscConj)
        self.mascEdit.setGeometry(QtCore.QRect(50, 130, 330, 30))
        self.mascEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mascEdit.setObjectName("mascEdit")
        self.femLbl = QtWidgets.QLabel(MiscConj)
        self.femLbl.setGeometry(QtCore.QRect(420, 110, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.femLbl.setFont(font)
        self.femLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.femLbl.setObjectName("femLbl")
        self.mascLbl = QtWidgets.QLabel(MiscConj)
        self.mascLbl.setGeometry(QtCore.QRect(50, 110, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mascLbl.setFont(font)
        self.mascLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.mascLbl.setObjectName("mascLbl")
        self.nuetLbl = QtWidgets.QLabel(MiscConj)
        self.nuetLbl.setGeometry(QtCore.QRect(50, 160, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nuetLbl.setFont(font)
        self.nuetLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.nuetLbl.setObjectName("nuetLbl")
        self.ruFormImpLbl = QtWidgets.QLabel(MiscConj)
        self.ruFormImpLbl.setGeometry(QtCore.QRect(420, 460, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ruFormImpLbl.setFont(font)
        self.ruFormImpLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ruFormImpLbl.setObjectName("ruFormImpLbl")
        self.ruInfImpEdit = LineEditRU(MiscConj)
        self.ruInfImpEdit.setGeometry(QtCore.QRect(50, 490, 330, 30))
        self.ruInfImpEdit.setText("")
        self.ruInfImpEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ruInfImpEdit.setObjectName("ruInfImpEdit")
        self.ruInfImpLbl = QtWidgets.QLabel(MiscConj)
        self.ruInfImpLbl.setGeometry(QtCore.QRect(50, 460, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ruInfImpLbl.setFont(font)
        self.ruInfImpLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ruInfImpLbl.setObjectName("ruInfImpLbl")
        self.ruFormImpEdit = LineEditRU(MiscConj)
        self.ruFormImpEdit.setGeometry(QtCore.QRect(420, 490, 330, 30))
        self.ruFormImpEdit.setText("")
        self.ruFormImpEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ruFormImpEdit.setObjectName("ruFormImpEdit")
        self.quitBttn = QtWidgets.QPushButton(MiscConj)
        self.quitBttn.setGeometry(QtCore.QRect(130, 520, 150, 50))
        self.quitBttn.setObjectName("quitBttn")
        self.acceptBttn = QtWidgets.QPushButton(MiscConj)
        self.acceptBttn.setGeometry(QtCore.QRect(520, 520, 150, 50))
        self.acceptBttn.setObjectName("acceptBttn")
        self.backBttn = QtWidgets.QPushButton(MiscConj)
        self.backBttn.setGeometry(QtCore.QRect(330, 520, 150, 50))
        self.backBttn.setObjectName("backBttn")
        self.helpBttn = QtWidgets.QPushButton(MiscConj)
        self.helpBttn.setGeometry(QtCore.QRect(630, 0, 150, 50))
        self.helpBttn.setObjectName("helpBttn")
        self.presAdv = LineEditRU(MiscConj)
        self.presAdv.setGeometry(QtCore.QRect(420, 370, 330, 30))
        self.presAdv.setText("")
        self.presAdv.setAlignment(QtCore.Qt.AlignCenter)
        self.presAdv.setObjectName("presAdv")
        self.enImpEdit = LineEditEN(MiscConj)
        self.enImpEdit.setGeometry(QtCore.QRect(420, 430, 330, 30))
        self.enImpEdit.setText("")
        self.enImpEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.enImpEdit.setObjectName("enImpEdit")
        self.enPastAdvLbl = QtWidgets.QLabel(MiscConj)
        self.enPastAdvLbl.setGeometry(QtCore.QRect(50, 280, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enPastAdvLbl.setFont(font)
        self.enPastAdvLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.enPastAdvLbl.setObjectName("enPastAdvLbl")
        self.enPastAdvEdit = LineEditEN(MiscConj)
        self.enPastAdvEdit.setGeometry(QtCore.QRect(420, 280, 330, 30))
        self.enPastAdvEdit.setText("")
        self.enPastAdvEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.enPastAdvEdit.setObjectName("enPastAdvEdit")
        self.advCheck = QtWidgets.QCheckBox(MiscConj)
        self.advCheck.setGeometry(QtCore.QRect(300, 220, 200, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.advCheck.setFont(font)
        self.advCheck.setChecked(True)
        self.advCheck.setObjectName("advCheck")
        self.stemEdit = LineEditRU(MiscConj)
        self.stemEdit.setGeometry(QtCore.QRect(420, 80, 330, 30))
        self.stemEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.stemEdit.setObjectName("stemEdit")
        self.stemLbl = QtWidgets.QLabel(MiscConj)
        self.stemLbl.setGeometry(QtCore.QRect(60, 80, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stemLbl.setFont(font)
        self.stemLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.stemLbl.setObjectName("stemLbl")
        self.enPresAdvEdit = LineEditEN(MiscConj)
        self.enPresAdvEdit.setGeometry(QtCore.QRect(420, 250, 330, 30))
        self.enPresAdvEdit.setText("")
        self.enPresAdvEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.enPresAdvEdit.setObjectName("enPresAdvEdit")
        self.enPresAdvLbl = QtWidgets.QLabel(MiscConj)
        self.enPresAdvLbl.setGeometry(QtCore.QRect(50, 250, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enPresAdvLbl.setFont(font)
        self.enPresAdvLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.enPresAdvLbl.setObjectName("enPresAdvLbl")
        self.presAdvLbl = QtWidgets.QLabel(MiscConj)
        self.presAdvLbl.setGeometry(QtCore.QRect(50, 370, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.presAdvLbl.setFont(font)
        self.presAdvLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.presAdvLbl.setObjectName("presAdvLbl")
        self.pastAdvLbl1 = QtWidgets.QLabel(MiscConj)
        self.pastAdvLbl1.setGeometry(QtCore.QRect(40, 340, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pastAdvLbl1.setFont(font)
        self.pastAdvLbl1.setAlignment(QtCore.Qt.AlignCenter)
        self.pastAdvLbl1.setObjectName("pastAdvLbl1")
        self.pastAdv1 = LineEditRU(MiscConj)
        self.pastAdv1.setGeometry(QtCore.QRect(420, 340, 330, 30))
        self.pastAdv1.setText("")
        self.pastAdv1.setAlignment(QtCore.Qt.AlignCenter)
        self.pastAdv1.setObjectName("pastAdv1")
        self.pastAdvLbl = QtWidgets.QLabel(MiscConj)
        self.pastAdvLbl.setGeometry(QtCore.QRect(40, 310, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pastAdvLbl.setFont(font)
        self.pastAdvLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.pastAdvLbl.setObjectName("pastAdvLbl")
        self.pastAdv = LineEditRU(MiscConj)
        self.pastAdv.setGeometry(QtCore.QRect(420, 310, 330, 30))
        self.pastAdv.setText("")
        self.pastAdv.setAlignment(QtCore.Qt.AlignCenter)
        self.pastAdv.setObjectName("pastAdv")
        self.enPPPEdit = LineEditEN(MiscConj)
        self.enPPPEdit.setGeometry(QtCore.QRect(420, 50, 330, 30))
        self.enPPPEdit.setText("")
        self.enPPPEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.enPPPEdit.setObjectName("enPPPEdit")
        self.enPPPLbl = QtWidgets.QLabel(MiscConj)
        self.enPPPLbl.setGeometry(QtCore.QRect(50, 50, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enPPPLbl.setFont(font)
        self.enPPPLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.enPPPLbl.setObjectName("enPPPLbl")
        self.spppCheck = QtWidgets.QCheckBox(MiscConj)
        self.spppCheck.setGeometry(QtCore.QRect(270, 20, 260, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.spppCheck.setFont(font)
        self.spppCheck.setChecked(True)
        self.spppCheck.setObjectName("spppCheck")
        self.impCheck = QtWidgets.QCheckBox(MiscConj)
        self.impCheck.setGeometry(QtCore.QRect(300, 400, 200, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.impCheck.setFont(font)
        self.impCheck.setChecked(True)
        self.impCheck.setObjectName("impCheck")

        self.retranslateUi(MiscConj)
        QtCore.QMetaObject.connectSlotsByName(MiscConj)
        MiscConj.setTabOrder(self.spppCheck, self.helpBttn)
        MiscConj.setTabOrder(self.helpBttn, self.enPPPEdit)
        MiscConj.setTabOrder(self.enPPPEdit, self.stemEdit)
        MiscConj.setTabOrder(self.stemEdit, self.mascEdit)
        MiscConj.setTabOrder(self.mascEdit, self.femEdit)
        MiscConj.setTabOrder(self.femEdit, self.nuetEdit)
        MiscConj.setTabOrder(self.nuetEdit, self.plurEdit)
        MiscConj.setTabOrder(self.plurEdit, self.advCheck)
        MiscConj.setTabOrder(self.advCheck, self.enPresAdvEdit)
        MiscConj.setTabOrder(self.enPresAdvEdit, self.enPastAdvEdit)
        MiscConj.setTabOrder(self.enPastAdvEdit, self.pastAdv)
        MiscConj.setTabOrder(self.pastAdv, self.pastAdv1)
        MiscConj.setTabOrder(self.pastAdv1, self.presAdv)
        MiscConj.setTabOrder(self.presAdv, self.enImpEdit)
        MiscConj.setTabOrder(self.enImpEdit, self.ruInfImpEdit)
        MiscConj.setTabOrder(self.ruInfImpEdit, self.ruFormImpEdit)
        MiscConj.setTabOrder(self.ruFormImpEdit, self.quitBttn)
        MiscConj.setTabOrder(self.quitBttn, self.backBttn)
        MiscConj.setTabOrder(self.backBttn, self.acceptBttn)

    def retranslateUi(self, MiscConj):
        _translate = QtCore.QCoreApplication.translate
        MiscConj.setWindowTitle(_translate("MiscConj", "Miscellaneous Conjugations"))
        self.enImpLbl.setText(_translate("MiscConj", "English Imperative"))
        self.plurLbl.setText(_translate("MiscConj", "Plural"))
        self.femLbl.setText(_translate("MiscConj", "Feminine"))
        self.mascLbl.setText(_translate("MiscConj", "Masculine"))
        self.nuetLbl.setText(_translate("MiscConj", "Nueter"))
        self.ruFormImpLbl.setText(_translate("MiscConj", "Russian Formal Imperative"))
        self.ruInfImpLbl.setText(_translate("MiscConj", "Russian Informal Imperative"))
        self.quitBttn.setText(_translate("MiscConj", "Quit"))
        self.acceptBttn.setText(_translate("MiscConj", "Accept."))
        self.backBttn.setText(_translate("MiscConj", "Back"))
        self.helpBttn.setText(_translate("MiscConj", "Help"))
        self.enPastAdvLbl.setText(_translate("MiscConj", "English Past Adverb"))
        self.advCheck.setText(_translate("MiscConj", "Verbal Adverb"))
        self.stemLbl.setText(_translate("MiscConj", "Participle Stem"))
        self.enPresAdvLbl.setText(_translate("MiscConj", "English Present Adverb"))
        self.presAdvLbl.setText(_translate("MiscConj", "Russian Present Adverb"))
        self.pastAdvLbl1.setText(_translate("MiscConj", "  Russian Past Adverb вш"))
        self.pastAdvLbl.setText(_translate("MiscConj", "Russian Past Adverb в"))
        self.enPPPLbl.setText(_translate("MiscConj", "English Past Passive"))
        self.spppCheck.setText(_translate("MiscConj", "Short Past Passive"))
        self.impCheck.setText(_translate("MiscConj", "Imperative"))

from machinetrans.lineeditru import LineEditRU
from machinetrans.lineediten import LineEditEN
