# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/pronoundecl.ui'
#
# Created: Thu Jan 25 11:35:27 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PronounDecl(object):
    def setupUi(self, PronounDecl):
        PronounDecl.setObjectName("PronounDecl")
        PronounDecl.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/machinetrans/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PronounDecl.setWindowIcon(icon)
        self.titleLbl = QtWidgets.QLabel(PronounDecl)
        self.titleLbl.setGeometry(QtCore.QRect(10, 10, 780, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.nomEdit = LineEditRU(PronounDecl)
        self.nomEdit.setGeometry(QtCore.QRect(30, 310, 340, 30))
        self.nomEdit.setObjectName("nomEdit")
        self.nomLbl = QtWidgets.QLabel(PronounDecl)
        self.nomLbl.setGeometry(QtCore.QRect(30, 280, 340, 25))
        self.nomLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.nomLbl.setObjectName("nomLbl")
        self.genLbl = QtWidgets.QLabel(PronounDecl)
        self.genLbl.setGeometry(QtCore.QRect(30, 350, 340, 25))
        self.genLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.genLbl.setObjectName("genLbl")
        self.genEdit = LineEditRU(PronounDecl)
        self.genEdit.setGeometry(QtCore.QRect(30, 380, 340, 30))
        self.genEdit.setObjectName("genEdit")
        self.insLbl = QtWidgets.QLabel(PronounDecl)
        self.insLbl.setGeometry(QtCore.QRect(30, 420, 340, 25))
        self.insLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.insLbl.setObjectName("insLbl")
        self.insEdit = LineEditRU(PronounDecl)
        self.insEdit.setGeometry(QtCore.QRect(30, 450, 340, 30))
        self.insEdit.setObjectName("insEdit")
        self.accLbl = QtWidgets.QLabel(PronounDecl)
        self.accLbl.setGeometry(QtCore.QRect(430, 280, 340, 25))
        self.accLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.accLbl.setObjectName("accLbl")
        self.accEdit = LineEditRU(PronounDecl)
        self.accEdit.setGeometry(QtCore.QRect(430, 310, 340, 30))
        self.accEdit.setObjectName("accEdit")
        self.datLbl = QtWidgets.QLabel(PronounDecl)
        self.datLbl.setGeometry(QtCore.QRect(430, 350, 340, 25))
        self.datLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.datLbl.setObjectName("datLbl")
        self.datEdit = LineEditRU(PronounDecl)
        self.datEdit.setGeometry(QtCore.QRect(430, 380, 340, 30))
        self.datEdit.setObjectName("datEdit")
        self.prpLbl = QtWidgets.QLabel(PronounDecl)
        self.prpLbl.setGeometry(QtCore.QRect(430, 420, 340, 25))
        self.prpLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.prpLbl.setObjectName("prpLbl")
        self.prpEdit = LineEditRU(PronounDecl)
        self.prpEdit.setGeometry(QtCore.QRect(430, 450, 340, 30))
        self.prpEdit.setObjectName("prpEdit")
        self.rejectBttn = QtWidgets.QPushButton(PronounDecl)
        self.rejectBttn.setGeometry(QtCore.QRect(30, 530, 150, 50))
        self.rejectBttn.setObjectName("rejectBttn")
        self.acceptBttn = QtWidgets.QPushButton(PronounDecl)
        self.acceptBttn.setGeometry(QtCore.QRect(620, 530, 150, 50))
        self.acceptBttn.setObjectName("acceptBttn")
        self.pronBttn = QtWidgets.QPushButton(PronounDecl)
        self.pronBttn.setGeometry(QtCore.QRect(420, 530, 150, 50))
        self.pronBttn.setObjectName("pronBttn")
        self.typeLbl = QtWidgets.QLabel(PronounDecl)
        self.typeLbl.setGeometry(QtCore.QRect(40, 170, 180, 25))
        self.typeLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.typeLbl.setObjectName("typeLbl")
        self.typeDrop = QtWidgets.QComboBox(PronounDecl)
        self.typeDrop.setGeometry(QtCore.QRect(40, 200, 180, 35))
        self.typeDrop.setObjectName("typeDrop")
        self.helpBttn = QtWidgets.QPushButton(PronounDecl)
        self.helpBttn.setGeometry(QtCore.QRect(640, 10, 150, 50))
        self.helpBttn.setObjectName("helpBttn")
        self.endingBttn = QtWidgets.QPushButton(PronounDecl)
        self.endingBttn.setGeometry(QtCore.QRect(230, 530, 150, 50))
        self.endingBttn.setObjectName("endingBttn")
        self.stemLbl = QtWidgets.QLabel(PronounDecl)
        self.stemLbl.setGeometry(QtCore.QRect(30, 240, 340, 25))
        self.stemLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stemLbl.setObjectName("stemLbl")
        self.stemEdit = LineEditRU(PronounDecl)
        self.stemEdit.setGeometry(QtCore.QRect(430, 240, 340, 30))
        self.stemEdit.setObjectName("stemEdit")
        self.enEdit = LineEditEN(PronounDecl)
        self.enEdit.setGeometry(QtCore.QRect(430, 200, 340, 30))
        self.enEdit.setObjectName("enEdit")
        self.enLbl = QtWidgets.QLabel(PronounDecl)
        self.enLbl.setGeometry(QtCore.QRect(240, 200, 130, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enLbl.setFont(font)
        self.enLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.enLbl.setObjectName("enLbl")
        self.genderBox = QtWidgets.QGroupBox(PronounDecl)
        self.genderBox.setGeometry(QtCore.QRect(10, 70, 780, 80))
        self.genderBox.setTitle("")
        self.genderBox.setObjectName("genderBox")
        self.mascanimrb = QtWidgets.QRadioButton(self.genderBox)
        self.mascanimrb.setGeometry(QtCore.QRect(10, 20, 250, 25))
        self.mascanimrb.setChecked(False)
        self.mascanimrb.setObjectName("mascanimrb")
        self.mascinanrb = QtWidgets.QRadioButton(self.genderBox)
        self.mascinanrb.setGeometry(QtCore.QRect(280, 20, 250, 25))
        self.mascinanrb.setChecked(True)
        self.mascinanrb.setObjectName("mascinanrb")
        self.femrb = QtWidgets.QRadioButton(self.genderBox)
        self.femrb.setGeometry(QtCore.QRect(620, 20, 130, 25))
        self.femrb.setChecked(False)
        self.femrb.setObjectName("femrb")
        self.plurinanrb = QtWidgets.QRadioButton(self.genderBox)
        self.plurinanrb.setGeometry(QtCore.QRect(550, 50, 200, 25))
        self.plurinanrb.setChecked(False)
        self.plurinanrb.setObjectName("plurinanrb")
        self.pluranimrb = QtWidgets.QRadioButton(self.genderBox)
        self.pluranimrb.setGeometry(QtCore.QRect(280, 50, 200, 25))
        self.pluranimrb.setObjectName("pluranimrb")
        self.nuetrb = QtWidgets.QRadioButton(self.genderBox)
        self.nuetrb.setGeometry(QtCore.QRect(10, 50, 150, 25))
        self.nuetrb.setChecked(False)
        self.nuetrb.setObjectName("nuetrb")
        self.singBttn = QtWidgets.QPushButton(PronounDecl)
        self.singBttn.setGeometry(QtCore.QRect(130, 480, 150, 50))
        self.singBttn.setObjectName("singBttn")
        self.groupBttn = QtWidgets.QPushButton(PronounDecl)
        self.groupBttn.setGeometry(QtCore.QRect(520, 480, 150, 50))
        self.groupBttn.setObjectName("groupBttn")

        self.retranslateUi(PronounDecl)
        QtCore.QMetaObject.connectSlotsByName(PronounDecl)
        PronounDecl.setTabOrder(self.helpBttn, self.mascanimrb)
        PronounDecl.setTabOrder(self.mascanimrb, self.mascinanrb)
        PronounDecl.setTabOrder(self.mascinanrb, self.femrb)
        PronounDecl.setTabOrder(self.femrb, self.nuetrb)
        PronounDecl.setTabOrder(self.nuetrb, self.pluranimrb)
        PronounDecl.setTabOrder(self.pluranimrb, self.plurinanrb)
        PronounDecl.setTabOrder(self.plurinanrb, self.typeDrop)
        PronounDecl.setTabOrder(self.typeDrop, self.enEdit)
        PronounDecl.setTabOrder(self.enEdit, self.stemEdit)
        PronounDecl.setTabOrder(self.stemEdit, self.nomEdit)
        PronounDecl.setTabOrder(self.nomEdit, self.accEdit)
        PronounDecl.setTabOrder(self.accEdit, self.genEdit)
        PronounDecl.setTabOrder(self.genEdit, self.datEdit)
        PronounDecl.setTabOrder(self.datEdit, self.insEdit)
        PronounDecl.setTabOrder(self.insEdit, self.prpEdit)
        PronounDecl.setTabOrder(self.prpEdit, self.singBttn)
        PronounDecl.setTabOrder(self.singBttn, self.groupBttn)
        PronounDecl.setTabOrder(self.groupBttn, self.rejectBttn)
        PronounDecl.setTabOrder(self.rejectBttn, self.endingBttn)
        PronounDecl.setTabOrder(self.endingBttn, self.pronBttn)
        PronounDecl.setTabOrder(self.pronBttn, self.acceptBttn)

    def retranslateUi(self, PronounDecl):
        _translate = QtCore.QCoreApplication.translate
        PronounDecl.setWindowTitle(_translate("PronounDecl", "Russian Pronoun Declension"))
        self.titleLbl.setText(_translate("PronounDecl", "Russian Pronoun Declension"))
        self.nomLbl.setText(_translate("PronounDecl", "Nominative"))
        self.genLbl.setText(_translate("PronounDecl", "Genitive"))
        self.insLbl.setText(_translate("PronounDecl", "Instrumental"))
        self.accLbl.setText(_translate("PronounDecl", "Accusative"))
        self.datLbl.setText(_translate("PronounDecl", "Dative"))
        self.prpLbl.setText(_translate("PronounDecl", "Prepositional"))
        self.rejectBttn.setText(_translate("PronounDecl", "Reject"))
        self.acceptBttn.setText(_translate("PronounDecl", "Accept"))
        self.pronBttn.setText(_translate("PronounDecl", "Pronouns"))
        self.typeLbl.setText(_translate("PronounDecl", "Pronoun Type"))
        self.helpBttn.setText(_translate("PronounDecl", "Help"))
        self.endingBttn.setText(_translate("PronounDecl", "Endings"))
        self.stemLbl.setText(_translate("PronounDecl", "Pronoun Stem"))
        self.enLbl.setText(_translate("PronounDecl", "English"))
        self.mascanimrb.setText(_translate("PronounDecl", "Masculine Animate"))
        self.mascinanrb.setText(_translate("PronounDecl", "Masculine Inanimate"))
        self.femrb.setText(_translate("PronounDecl", "Feminine"))
        self.plurinanrb.setText(_translate("PronounDecl", "Plural Inanimate"))
        self.pluranimrb.setText(_translate("PronounDecl", "Plural Animate"))
        self.nuetrb.setText(_translate("PronounDecl", "Nueter"))
        self.singBttn.setText(_translate("PronounDecl", "Singular"))
        self.groupBttn.setText(_translate("PronounDecl", "Group"))

from machinetrans.lineeditru import LineEditRU
from machinetrans.lineediten import LineEditEN
