# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/partdecl.ui'
#
# Created: Thu Jan 25 11:35:25 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PartDecl(object):
    def setupUi(self, PartDecl):
        PartDecl.setObjectName("PartDecl")
        PartDecl.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/machinetrans/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PartDecl.setWindowIcon(icon)
        self.insEdit = LineEditRU(PartDecl)
        self.insEdit.setGeometry(QtCore.QRect(30, 330, 340, 30))
        self.insEdit.setText("")
        self.insEdit.setObjectName("insEdit")
        self.insLbl = QtWidgets.QLabel(PartDecl)
        self.insLbl.setGeometry(QtCore.QRect(30, 310, 340, 25))
        self.insLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.insLbl.setObjectName("insLbl")
        self.accEdit = LineEditRU(PartDecl)
        self.accEdit.setGeometry(QtCore.QRect(430, 210, 340, 30))
        self.accEdit.setObjectName("accEdit")
        self.genLbl = QtWidgets.QLabel(PartDecl)
        self.genLbl.setGeometry(QtCore.QRect(30, 250, 340, 25))
        self.genLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.genLbl.setObjectName("genLbl")
        self.datLbl = QtWidgets.QLabel(PartDecl)
        self.datLbl.setGeometry(QtCore.QRect(430, 250, 340, 25))
        self.datLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.datLbl.setObjectName("datLbl")
        self.prpLbl = QtWidgets.QLabel(PartDecl)
        self.prpLbl.setGeometry(QtCore.QRect(430, 310, 340, 25))
        self.prpLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.prpLbl.setObjectName("prpLbl")
        self.datEdit = LineEditRU(PartDecl)
        self.datEdit.setGeometry(QtCore.QRect(430, 270, 340, 30))
        self.datEdit.setObjectName("datEdit")
        self.accLbl = QtWidgets.QLabel(PartDecl)
        self.accLbl.setGeometry(QtCore.QRect(430, 190, 340, 25))
        self.accLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.accLbl.setObjectName("accLbl")
        self.nomLbl = QtWidgets.QLabel(PartDecl)
        self.nomLbl.setGeometry(QtCore.QRect(30, 190, 340, 25))
        self.nomLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.nomLbl.setObjectName("nomLbl")
        self.nomEdit = LineEditRU(PartDecl)
        self.nomEdit.setGeometry(QtCore.QRect(30, 210, 340, 30))
        self.nomEdit.setObjectName("nomEdit")
        self.genEdit = LineEditRU(PartDecl)
        self.genEdit.setGeometry(QtCore.QRect(30, 270, 340, 30))
        self.genEdit.setObjectName("genEdit")
        self.prpEdit = LineEditRU(PartDecl)
        self.prpEdit.setGeometry(QtCore.QRect(430, 330, 340, 30))
        self.prpEdit.setObjectName("prpEdit")
        self.tenseBox = QtWidgets.QGroupBox(PartDecl)
        self.tenseBox.setGeometry(QtCore.QRect(10, 40, 780, 40))
        self.tenseBox.setTitle("")
        self.tenseBox.setObjectName("tenseBox")
        self.parb = QtWidgets.QRadioButton(self.tenseBox)
        self.parb.setGeometry(QtCore.QRect(20, 20, 170, 25))
        self.parb.setChecked(True)
        self.parb.setObjectName("parb")
        self.pprb = QtWidgets.QRadioButton(self.tenseBox)
        self.pprb.setGeometry(QtCore.QRect(210, 20, 170, 25))
        self.pprb.setObjectName("pprb")
        self.pastarb = QtWidgets.QRadioButton(self.tenseBox)
        self.pastarb.setGeometry(QtCore.QRect(430, 20, 170, 21))
        self.pastarb.setObjectName("pastarb")
        self.pastprb = QtWidgets.QRadioButton(self.tenseBox)
        self.pastprb.setGeometry(QtCore.QRect(600, 20, 170, 25))
        self.pastprb.setObjectName("pastprb")
        self.quitBttn = QtWidgets.QPushButton(PartDecl)
        self.quitBttn.setGeometry(QtCore.QRect(100, 530, 150, 50))
        self.quitBttn.setObjectName("quitBttn")
        self.acceptBttn = QtWidgets.QPushButton(PartDecl)
        self.acceptBttn.setGeometry(QtCore.QRect(550, 530, 150, 50))
        self.acceptBttn.setObjectName("acceptBttn")
        self.titleLbl = QtWidgets.QLabel(PartDecl)
        self.titleLbl.setGeometry(QtCore.QRect(10, 10, 780, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.enLbl = QtWidgets.QLabel(PartDecl)
        self.enLbl.setGeometry(QtCore.QRect(30, 470, 80, 25))
        self.enLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.enLbl.setObjectName("enLbl")
        self.backBttn = QtWidgets.QPushButton(PartDecl)
        self.backBttn.setGeometry(QtCore.QRect(320, 530, 150, 50))
        self.backBttn.setObjectName("backBttn")
        self.genderBox = QtWidgets.QGroupBox(PartDecl)
        self.genderBox.setGeometry(QtCore.QRect(10, 90, 780, 90))
        self.genderBox.setTitle("")
        self.genderBox.setObjectName("genderBox")
        self.mascanimrb = QtWidgets.QRadioButton(self.genderBox)
        self.mascanimrb.setGeometry(QtCore.QRect(70, 20, 200, 25))
        self.mascanimrb.setChecked(False)
        self.mascanimrb.setObjectName("mascanimrb")
        self.femrb = QtWidgets.QRadioButton(self.genderBox)
        self.femrb.setGeometry(QtCore.QRect(580, 20, 150, 25))
        self.femrb.setObjectName("femrb")
        self.nuetrb = QtWidgets.QRadioButton(self.genderBox)
        self.nuetrb.setGeometry(QtCore.QRect(70, 50, 150, 25))
        self.nuetrb.setObjectName("nuetrb")
        self.pluranimrb = QtWidgets.QRadioButton(self.genderBox)
        self.pluranimrb.setGeometry(QtCore.QRect(300, 50, 200, 25))
        self.pluranimrb.setObjectName("pluranimrb")
        self.mascinanrb = QtWidgets.QRadioButton(self.genderBox)
        self.mascinanrb.setGeometry(QtCore.QRect(300, 20, 200, 25))
        self.mascinanrb.setChecked(True)
        self.mascinanrb.setObjectName("mascinanrb")
        self.plurinanrb = QtWidgets.QRadioButton(self.genderBox)
        self.plurinanrb.setGeometry(QtCore.QRect(530, 50, 200, 25))
        self.plurinanrb.setObjectName("plurinanrb")
        self.presaCheck = QtWidgets.QCheckBox(PartDecl)
        self.presaCheck.setGeometry(QtCore.QRect(80, 360, 200, 30))
        self.presaCheck.setObjectName("presaCheck")
        self.prespCheck = QtWidgets.QCheckBox(PartDecl)
        self.prespCheck.setGeometry(QtCore.QRect(80, 390, 200, 30))
        self.prespCheck.setObjectName("prespCheck")
        self.pastpCheck = QtWidgets.QCheckBox(PartDecl)
        self.pastpCheck.setGeometry(QtCore.QRect(480, 390, 200, 30))
        self.pastpCheck.setObjectName("pastpCheck")
        self.pastaCheck = QtWidgets.QCheckBox(PartDecl)
        self.pastaCheck.setGeometry(QtCore.QRect(480, 360, 200, 30))
        self.pastaCheck.setObjectName("pastaCheck")
        self.stemEdit = LineEditRU(PartDecl)
        self.stemEdit.setGeometry(QtCore.QRect(160, 420, 230, 30))
        self.stemEdit.setText("")
        self.stemEdit.setObjectName("stemEdit")
        self.stemLbl = QtWidgets.QLabel(PartDecl)
        self.stemLbl.setGeometry(QtCore.QRect(60, 420, 80, 25))
        self.stemLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.stemLbl.setObjectName("stemLbl")
        self.endLbl = QtWidgets.QLabel(PartDecl)
        self.endLbl.setGeometry(QtCore.QRect(410, 420, 80, 25))
        self.endLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.endLbl.setObjectName("endLbl")
        self.endEdit = LineEditRU(PartDecl)
        self.endEdit.setGeometry(QtCore.QRect(510, 420, 230, 30))
        self.endEdit.setText("")
        self.endEdit.setObjectName("endEdit")
        self.helpBttn = QtWidgets.QPushButton(PartDecl)
        self.helpBttn.setGeometry(QtCore.QRect(640, 0, 150, 50))
        self.helpBttn.setObjectName("helpBttn")
        self.enEdit = LineEditEN(PartDecl)
        self.enEdit.setGeometry(QtCore.QRect(130, 470, 330, 30))
        self.enEdit.setText("")
        self.enEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.enEdit.setObjectName("enEdit")
        self.changeBttn = QtWidgets.QPushButton(PartDecl)
        self.changeBttn.setGeometry(QtCore.QRect(530, 460, 150, 50))
        self.changeBttn.setObjectName("changeBttn")

        self.retranslateUi(PartDecl)
        QtCore.QMetaObject.connectSlotsByName(PartDecl)
        PartDecl.setTabOrder(self.helpBttn, self.parb)
        PartDecl.setTabOrder(self.parb, self.pprb)
        PartDecl.setTabOrder(self.pprb, self.pastarb)
        PartDecl.setTabOrder(self.pastarb, self.pastprb)
        PartDecl.setTabOrder(self.pastprb, self.mascanimrb)
        PartDecl.setTabOrder(self.mascanimrb, self.mascinanrb)
        PartDecl.setTabOrder(self.mascinanrb, self.femrb)
        PartDecl.setTabOrder(self.femrb, self.nuetrb)
        PartDecl.setTabOrder(self.nuetrb, self.pluranimrb)
        PartDecl.setTabOrder(self.pluranimrb, self.plurinanrb)
        PartDecl.setTabOrder(self.plurinanrb, self.nomEdit)
        PartDecl.setTabOrder(self.nomEdit, self.accEdit)
        PartDecl.setTabOrder(self.accEdit, self.genEdit)
        PartDecl.setTabOrder(self.genEdit, self.datEdit)
        PartDecl.setTabOrder(self.datEdit, self.insEdit)
        PartDecl.setTabOrder(self.insEdit, self.prpEdit)
        PartDecl.setTabOrder(self.prpEdit, self.presaCheck)
        PartDecl.setTabOrder(self.presaCheck, self.pastaCheck)
        PartDecl.setTabOrder(self.pastaCheck, self.prespCheck)
        PartDecl.setTabOrder(self.prespCheck, self.pastpCheck)
        PartDecl.setTabOrder(self.pastpCheck, self.stemEdit)
        PartDecl.setTabOrder(self.stemEdit, self.endEdit)
        PartDecl.setTabOrder(self.endEdit, self.enEdit)
        PartDecl.setTabOrder(self.enEdit, self.quitBttn)
        PartDecl.setTabOrder(self.quitBttn, self.backBttn)
        PartDecl.setTabOrder(self.backBttn, self.acceptBttn)

    def retranslateUi(self, PartDecl):
        _translate = QtCore.QCoreApplication.translate
        PartDecl.setWindowTitle(_translate("PartDecl", "Russian Participial Declension"))
        self.insLbl.setText(_translate("PartDecl", "Instrumental"))
        self.genLbl.setText(_translate("PartDecl", "Genitive"))
        self.datLbl.setText(_translate("PartDecl", "Dative"))
        self.prpLbl.setText(_translate("PartDecl", "Prepositional"))
        self.accLbl.setText(_translate("PartDecl", "Accusative"))
        self.nomLbl.setText(_translate("PartDecl", "Nominative"))
        self.parb.setText(_translate("PartDecl", "Pres Active"))
        self.pprb.setText(_translate("PartDecl", "Pres Passive"))
        self.pastarb.setText(_translate("PartDecl", "Past Active"))
        self.pastprb.setText(_translate("PartDecl", "Past Passive"))
        self.quitBttn.setText(_translate("PartDecl", "Quit"))
        self.acceptBttn.setText(_translate("PartDecl", "Accept"))
        self.titleLbl.setText(_translate("PartDecl", "Russian Participial Declension For"))
        self.enLbl.setText(_translate("PartDecl", "English"))
        self.backBttn.setText(_translate("PartDecl", "Back"))
        self.mascanimrb.setText(_translate("PartDecl", "Masc Animate"))
        self.femrb.setText(_translate("PartDecl", "Feminine"))
        self.nuetrb.setText(_translate("PartDecl", "Nueter"))
        self.pluranimrb.setText(_translate("PartDecl", "Plural Animate"))
        self.mascinanrb.setText(_translate("PartDecl", "Masc Inanimate"))
        self.plurinanrb.setText(_translate("PartDecl", "Plural Inanimate"))
        self.presaCheck.setText(_translate("PartDecl", "Present Active"))
        self.prespCheck.setText(_translate("PartDecl", "Present Passive"))
        self.pastpCheck.setText(_translate("PartDecl", "Past Passive"))
        self.pastaCheck.setText(_translate("PartDecl", "Past Active"))
        self.stemLbl.setText(_translate("PartDecl", "Stem"))
        self.endLbl.setText(_translate("PartDecl", "Ending"))
        self.helpBttn.setText(_translate("PartDecl", "Help"))
        self.changeBttn.setText(_translate("PartDecl", "Change All"))

from machinetrans.lineeditru import LineEditRU
from machinetrans.lineediten import LineEditEN
