# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/pastconj.ui'
#
# Created: Thu Jan 25 11:35:25 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PastConj(object):
    def setupUi(self, PastConj):
        PastConj.setObjectName("PastConj")
        PastConj.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/machinetrans/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PastConj.setWindowIcon(icon)
        self.rufemEdit = LineEditRU(PastConj)
        self.rufemEdit.setGeometry(QtCore.QRect(420, 150, 330, 30))
        self.rufemEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rufemEdit.setObjectName("rufemEdit")
        self.ruplurLbl = QtWidgets.QLabel(PastConj)
        self.ruplurLbl.setGeometry(QtCore.QRect(420, 190, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ruplurLbl.setFont(font)
        self.ruplurLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ruplurLbl.setObjectName("ruplurLbl")
        self.ruplurEdit = LineEditRU(PastConj)
        self.ruplurEdit.setGeometry(QtCore.QRect(420, 230, 330, 30))
        self.ruplurEdit.setText("")
        self.ruplurEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ruplurEdit.setObjectName("ruplurEdit")
        self.rutitleLbl = QtWidgets.QLabel(PastConj)
        self.rutitleLbl.setGeometry(QtCore.QRect(10, 20, 780, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rutitleLbl.setFont(font)
        self.rutitleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rutitleLbl.setObjectName("rutitleLbl")
        self.runuetEdit = LineEditRU(PastConj)
        self.runuetEdit.setGeometry(QtCore.QRect(50, 230, 330, 30))
        self.runuetEdit.setText("")
        self.runuetEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.runuetEdit.setObjectName("runuetEdit")
        self.rumascEdit = LineEditRU(PastConj)
        self.rumascEdit.setGeometry(QtCore.QRect(50, 150, 330, 30))
        self.rumascEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rumascEdit.setObjectName("rumascEdit")
        self.rufemLbl = QtWidgets.QLabel(PastConj)
        self.rufemLbl.setGeometry(QtCore.QRect(420, 120, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rufemLbl.setFont(font)
        self.rufemLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rufemLbl.setObjectName("rufemLbl")
        self.rumascLbl = QtWidgets.QLabel(PastConj)
        self.rumascLbl.setGeometry(QtCore.QRect(50, 120, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rumascLbl.setFont(font)
        self.rumascLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rumascLbl.setObjectName("rumascLbl")
        self.runuetLbl = QtWidgets.QLabel(PastConj)
        self.runuetLbl.setGeometry(QtCore.QRect(50, 190, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.runuetLbl.setFont(font)
        self.runuetLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.runuetLbl.setObjectName("runuetLbl")
        self.quitBttn = QtWidgets.QPushButton(PastConj)
        self.quitBttn.setGeometry(QtCore.QRect(130, 520, 150, 50))
        self.quitBttn.setObjectName("quitBttn")
        self.acceptBttn = QtWidgets.QPushButton(PastConj)
        self.acceptBttn.setGeometry(QtCore.QRect(520, 520, 150, 50))
        self.acceptBttn.setObjectName("acceptBttn")
        self.backBttn = QtWidgets.QPushButton(PastConj)
        self.backBttn.setGeometry(QtCore.QRect(330, 520, 150, 50))
        self.backBttn.setObjectName("backBttn")
        self.femEdit = LineEditEN(PastConj)
        self.femEdit.setGeometry(QtCore.QRect(420, 400, 330, 30))
        self.femEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.femEdit.setObjectName("femEdit")
        self.titleLbl = QtWidgets.QLabel(PastConj)
        self.titleLbl.setGeometry(QtCore.QRect(10, 270, 780, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.plurEdit = LineEditEN(PastConj)
        self.plurEdit.setGeometry(QtCore.QRect(420, 470, 330, 30))
        self.plurEdit.setText("")
        self.plurEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.plurEdit.setObjectName("plurEdit")
        self.mascLbl = QtWidgets.QLabel(PastConj)
        self.mascLbl.setGeometry(QtCore.QRect(50, 370, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mascLbl.setFont(font)
        self.mascLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.mascLbl.setObjectName("mascLbl")
        self.femLbl = QtWidgets.QLabel(PastConj)
        self.femLbl.setGeometry(QtCore.QRect(420, 370, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.femLbl.setFont(font)
        self.femLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.femLbl.setObjectName("femLbl")
        self.mascEdit = LineEditEN(PastConj)
        self.mascEdit.setGeometry(QtCore.QRect(50, 400, 330, 30))
        self.mascEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.mascEdit.setObjectName("mascEdit")
        self.nuetEdit = LineEditEN(PastConj)
        self.nuetEdit.setGeometry(QtCore.QRect(50, 470, 330, 30))
        self.nuetEdit.setText("")
        self.nuetEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.nuetEdit.setObjectName("nuetEdit")
        self.plurLbl = QtWidgets.QLabel(PastConj)
        self.plurLbl.setGeometry(QtCore.QRect(420, 440, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.plurLbl.setFont(font)
        self.plurLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.plurLbl.setObjectName("plurLbl")
        self.nuetLbl = QtWidgets.QLabel(PastConj)
        self.nuetLbl.setGeometry(QtCore.QRect(50, 440, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nuetLbl.setFont(font)
        self.nuetLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.nuetLbl.setObjectName("nuetLbl")
        self.helpBttn = QtWidgets.QPushButton(PastConj)
        self.helpBttn.setGeometry(QtCore.QRect(630, 10, 150, 50))
        self.helpBttn.setObjectName("helpBttn")
        self.stemLbl = QtWidgets.QLabel(PastConj)
        self.stemLbl.setGeometry(QtCore.QRect(50, 80, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stemLbl.setFont(font)
        self.stemLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stemLbl.setObjectName("stemLbl")
        self.stemEdit = LineEditRU(PastConj)
        self.stemEdit.setGeometry(QtCore.QRect(420, 80, 330, 30))
        self.stemEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.stemEdit.setObjectName("stemEdit")
        self.verbLbl = QtWidgets.QLabel(PastConj)
        self.verbLbl.setGeometry(QtCore.QRect(50, 330, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.verbLbl.setFont(font)
        self.verbLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.verbLbl.setObjectName("verbLbl")
        self.verbEdit = LineEditEN(PastConj)
        self.verbEdit.setGeometry(QtCore.QRect(420, 330, 330, 30))
        self.verbEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.verbEdit.setObjectName("verbEdit")

        self.retranslateUi(PastConj)
        QtCore.QMetaObject.connectSlotsByName(PastConj)
        PastConj.setTabOrder(self.helpBttn, self.stemEdit)
        PastConj.setTabOrder(self.stemEdit, self.rumascEdit)
        PastConj.setTabOrder(self.rumascEdit, self.rufemEdit)
        PastConj.setTabOrder(self.rufemEdit, self.runuetEdit)
        PastConj.setTabOrder(self.runuetEdit, self.ruplurEdit)
        PastConj.setTabOrder(self.ruplurEdit, self.verbEdit)
        PastConj.setTabOrder(self.verbEdit, self.mascEdit)
        PastConj.setTabOrder(self.mascEdit, self.femEdit)
        PastConj.setTabOrder(self.femEdit, self.nuetEdit)
        PastConj.setTabOrder(self.nuetEdit, self.plurEdit)
        PastConj.setTabOrder(self.plurEdit, self.quitBttn)
        PastConj.setTabOrder(self.quitBttn, self.backBttn)
        PastConj.setTabOrder(self.backBttn, self.acceptBttn)

    def retranslateUi(self, PastConj):
        _translate = QtCore.QCoreApplication.translate
        PastConj.setWindowTitle(_translate("PastConj", "Russian Past Tense Conjugation"))
        self.ruplurLbl.setText(_translate("PastConj", "Plural"))
        self.rutitleLbl.setText(_translate("PastConj", "Russian Past Tense for "))
        self.rufemLbl.setText(_translate("PastConj", "Feminine"))
        self.rumascLbl.setText(_translate("PastConj", "Masculine"))
        self.runuetLbl.setText(_translate("PastConj", "Nueter"))
        self.quitBttn.setText(_translate("PastConj", "Quit"))
        self.acceptBttn.setText(_translate("PastConj", "Accept."))
        self.backBttn.setText(_translate("PastConj", "Back"))
        self.titleLbl.setText(_translate("PastConj", "English Past Tense for"))
        self.mascLbl.setText(_translate("PastConj", "Masculine"))
        self.femLbl.setText(_translate("PastConj", "Feminine"))
        self.plurLbl.setText(_translate("PastConj", "Plural"))
        self.nuetLbl.setText(_translate("PastConj", "Nueter"))
        self.helpBttn.setText(_translate("PastConj", "Help"))
        self.stemLbl.setText(_translate("PastConj", "Russian Verb Stem"))
        self.verbLbl.setText(_translate("PastConj", "Past Tense English Verb"))

from machinetrans.lineeditru import LineEditRU
from machinetrans.lineediten import LineEditEN
