# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/shortadj.ui'
#
# Created: Thu Jan 25 11:35:27 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ShortAdj(object):
    def setupUi(self, ShortAdj):
        ShortAdj.setObjectName("ShortAdj")
        ShortAdj.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/machinetrans/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ShortAdj.setWindowIcon(icon)
        self.rufemEdit = LineEditRU(ShortAdj)
        self.rufemEdit.setGeometry(QtCore.QRect(420, 140, 330, 30))
        self.rufemEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rufemEdit.setObjectName("rufemEdit")
        self.ruplurLbl = QtWidgets.QLabel(ShortAdj)
        self.ruplurLbl.setGeometry(QtCore.QRect(420, 210, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ruplurLbl.setFont(font)
        self.ruplurLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ruplurLbl.setObjectName("ruplurLbl")
        self.ruplurEdit = LineEditRU(ShortAdj)
        self.ruplurEdit.setGeometry(QtCore.QRect(420, 240, 330, 30))
        self.ruplurEdit.setText("")
        self.ruplurEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ruplurEdit.setObjectName("ruplurEdit")
        self.titleLbl = QtWidgets.QLabel(ShortAdj)
        self.titleLbl.setGeometry(QtCore.QRect(10, 20, 780, 60))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.runuetEdit = LineEditRU(ShortAdj)
        self.runuetEdit.setGeometry(QtCore.QRect(50, 240, 330, 30))
        self.runuetEdit.setText("")
        self.runuetEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.runuetEdit.setObjectName("runuetEdit")
        self.rumascEdit = LineEditRU(ShortAdj)
        self.rumascEdit.setGeometry(QtCore.QRect(50, 140, 330, 30))
        self.rumascEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rumascEdit.setObjectName("rumascEdit")
        self.rufemLbl = QtWidgets.QLabel(ShortAdj)
        self.rufemLbl.setGeometry(QtCore.QRect(420, 110, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rufemLbl.setFont(font)
        self.rufemLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rufemLbl.setObjectName("rufemLbl")
        self.rumascLbl = QtWidgets.QLabel(ShortAdj)
        self.rumascLbl.setGeometry(QtCore.QRect(50, 110, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rumascLbl.setFont(font)
        self.rumascLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.rumascLbl.setObjectName("rumascLbl")
        self.runuetLbl = QtWidgets.QLabel(ShortAdj)
        self.runuetLbl.setGeometry(QtCore.QRect(50, 210, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.runuetLbl.setFont(font)
        self.runuetLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.runuetLbl.setObjectName("runuetLbl")
        self.quitBttn = QtWidgets.QPushButton(ShortAdj)
        self.quitBttn.setGeometry(QtCore.QRect(130, 520, 150, 50))
        self.quitBttn.setObjectName("quitBttn")
        self.acceptBttn = QtWidgets.QPushButton(ShortAdj)
        self.acceptBttn.setGeometry(QtCore.QRect(520, 520, 150, 50))
        self.acceptBttn.setObjectName("acceptBttn")
        self.stemEdit = LineEditRU(ShortAdj)
        self.stemEdit.setGeometry(QtCore.QRect(230, 330, 330, 30))
        self.stemEdit.setText("")
        self.stemEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.stemEdit.setObjectName("stemEdit")
        self.engLbl = QtWidgets.QLabel(ShortAdj)
        self.engLbl.setGeometry(QtCore.QRect(230, 390, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.engLbl.setFont(font)
        self.engLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.engLbl.setObjectName("engLbl")
        self.stemLbl = QtWidgets.QLabel(ShortAdj)
        self.stemLbl.setGeometry(QtCore.QRect(230, 300, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stemLbl.setFont(font)
        self.stemLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.stemLbl.setObjectName("stemLbl")
        self.helpBttn = QtWidgets.QPushButton(ShortAdj)
        self.helpBttn.setGeometry(QtCore.QRect(640, 10, 150, 50))
        self.helpBttn.setObjectName("helpBttn")
        self.enEdit = LineEditEN(ShortAdj)
        self.enEdit.setGeometry(QtCore.QRect(230, 440, 330, 30))
        self.enEdit.setText("")
        self.enEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.enEdit.setObjectName("enEdit")
        self.backBttn = QtWidgets.QPushButton(ShortAdj)
        self.backBttn.setGeometry(QtCore.QRect(325, 520, 150, 50))
        self.backBttn.setObjectName("backBttn")
        self.shortCheck = QtWidgets.QCheckBox(ShortAdj)
        self.shortCheck.setGeometry(QtCore.QRect(320, 70, 160, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.shortCheck.setFont(font)
        self.shortCheck.setChecked(False)
        self.shortCheck.setObjectName("shortCheck")

        self.retranslateUi(ShortAdj)
        QtCore.QMetaObject.connectSlotsByName(ShortAdj)
        ShortAdj.setTabOrder(self.helpBttn, self.rumascEdit)
        ShortAdj.setTabOrder(self.rumascEdit, self.rufemEdit)
        ShortAdj.setTabOrder(self.rufemEdit, self.runuetEdit)
        ShortAdj.setTabOrder(self.runuetEdit, self.ruplurEdit)
        ShortAdj.setTabOrder(self.ruplurEdit, self.stemEdit)
        ShortAdj.setTabOrder(self.stemEdit, self.enEdit)
        ShortAdj.setTabOrder(self.enEdit, self.quitBttn)
        ShortAdj.setTabOrder(self.quitBttn, self.acceptBttn)

    def retranslateUi(self, ShortAdj):
        _translate = QtCore.QCoreApplication.translate
        ShortAdj.setWindowTitle(_translate("ShortAdj", "Russian Short Form Adjective"))
        self.ruplurLbl.setText(_translate("ShortAdj", "Plural"))
        self.titleLbl.setText(_translate("ShortAdj", "Russian Short Form Adjective for "))
        self.rufemLbl.setText(_translate("ShortAdj", "Feminine"))
        self.rumascLbl.setText(_translate("ShortAdj", "Masculine"))
        self.runuetLbl.setText(_translate("ShortAdj", "Nueter"))
        self.quitBttn.setText(_translate("ShortAdj", "Quit"))
        self.acceptBttn.setText(_translate("ShortAdj", "Accept."))
        self.engLbl.setText(_translate("ShortAdj", "English"))
        self.stemLbl.setText(_translate("ShortAdj", "Stem"))
        self.helpBttn.setText(_translate("ShortAdj", "Help"))
        self.backBttn.setText(_translate("ShortAdj", "Back"))
        self.shortCheck.setText(_translate("ShortAdj", "Short Form"))

from machinetrans.lineediten import LineEditEN
from machinetrans.lineeditru import LineEditRU
