# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/sortedkeys.ui'
#
# Created: Thu Jan 25 11:35:28 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SortedKeys(object):
    def setupUi(self, SortedKeys):
        SortedKeys.setObjectName("SortedKeys")
        SortedKeys.resize(800, 353)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SortedKeys.sizePolicy().hasHeightForWidth())
        SortedKeys.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/machinetrans/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SortedKeys.setWindowIcon(icon)
        self.key1 = QtWidgets.QComboBox(SortedKeys)
        self.key1.setEnabled(False)
        self.key1.setGeometry(QtCore.QRect(60, 80, 200, 35))
        self.key1.setObjectName("key1")
        self.key2 = QtWidgets.QComboBox(SortedKeys)
        self.key2.setEnabled(False)
        self.key2.setGeometry(QtCore.QRect(300, 80, 200, 34))
        self.key2.setObjectName("key2")
        self.key3 = QtWidgets.QComboBox(SortedKeys)
        self.key3.setEnabled(False)
        self.key3.setGeometry(QtCore.QRect(540, 80, 200, 34))
        self.key3.setObjectName("key3")
        self.key5 = QtWidgets.QComboBox(SortedKeys)
        self.key5.setEnabled(False)
        self.key5.setGeometry(QtCore.QRect(300, 150, 200, 34))
        self.key5.setObjectName("key5")
        self.key4 = QtWidgets.QComboBox(SortedKeys)
        self.key4.setEnabled(False)
        self.key4.setGeometry(QtCore.QRect(60, 150, 200, 34))
        self.key4.setObjectName("key4")
        self.key6 = QtWidgets.QComboBox(SortedKeys)
        self.key6.setEnabled(False)
        self.key6.setGeometry(QtCore.QRect(540, 150, 200, 34))
        self.key6.setObjectName("key6")
        self.key8 = QtWidgets.QComboBox(SortedKeys)
        self.key8.setEnabled(False)
        self.key8.setGeometry(QtCore.QRect(300, 220, 200, 34))
        self.key8.setObjectName("key8")
        self.key7 = QtWidgets.QComboBox(SortedKeys)
        self.key7.setEnabled(False)
        self.key7.setGeometry(QtCore.QRect(60, 220, 200, 34))
        self.key7.setObjectName("key7")
        self.key9 = QtWidgets.QComboBox(SortedKeys)
        self.key9.setEnabled(False)
        self.key9.setGeometry(QtCore.QRect(540, 220, 200, 34))
        self.key9.setObjectName("key9")
        self.quitBttn = QtWidgets.QPushButton(SortedKeys)
        self.quitBttn.setGeometry(QtCore.QRect(90, 260, 150, 50))
        self.quitBttn.setObjectName("quitBttn")
        self.acceptBttn = QtWidgets.QPushButton(SortedKeys)
        self.acceptBttn.setGeometry(QtCore.QRect(560, 260, 150, 50))
        self.acceptBttn.setObjectName("acceptBttn")
        self.helpBttn = QtWidgets.QPushButton(SortedKeys)
        self.helpBttn.setGeometry(QtCore.QRect(640, 0, 150, 50))
        self.helpBttn.setObjectName("helpBttn")
        self.titleLbl = QtWidgets.QLabel(SortedKeys)
        self.titleLbl.setGeometry(QtCore.QRect(200, 20, 411, 25))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.key1Lbl = QtWidgets.QLabel(SortedKeys)
        self.key1Lbl.setGeometry(QtCore.QRect(110, 50, 100, 25))
        self.key1Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.key1Lbl.setObjectName("key1Lbl")
        self.key2Lbl = QtWidgets.QLabel(SortedKeys)
        self.key2Lbl.setGeometry(QtCore.QRect(340, 50, 100, 25))
        self.key2Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.key2Lbl.setObjectName("key2Lbl")
        self.key3Lbl = QtWidgets.QLabel(SortedKeys)
        self.key3Lbl.setGeometry(QtCore.QRect(590, 50, 100, 25))
        self.key3Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.key3Lbl.setObjectName("key3Lbl")
        self.key4Lbl = QtWidgets.QLabel(SortedKeys)
        self.key4Lbl.setGeometry(QtCore.QRect(110, 120, 100, 25))
        self.key4Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.key4Lbl.setObjectName("key4Lbl")
        self.key5Lbl = QtWidgets.QLabel(SortedKeys)
        self.key5Lbl.setGeometry(QtCore.QRect(340, 120, 100, 25))
        self.key5Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.key5Lbl.setObjectName("key5Lbl")
        self.key6Lbl = QtWidgets.QLabel(SortedKeys)
        self.key6Lbl.setGeometry(QtCore.QRect(590, 120, 100, 25))
        self.key6Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.key6Lbl.setObjectName("key6Lbl")
        self.key7Lbl = QtWidgets.QLabel(SortedKeys)
        self.key7Lbl.setGeometry(QtCore.QRect(110, 190, 100, 25))
        self.key7Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.key7Lbl.setObjectName("key7Lbl")
        self.key8Lbl = QtWidgets.QLabel(SortedKeys)
        self.key8Lbl.setGeometry(QtCore.QRect(340, 190, 100, 25))
        self.key8Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.key8Lbl.setObjectName("key8Lbl")
        self.key9Lbl = QtWidgets.QLabel(SortedKeys)
        self.key9Lbl.setGeometry(QtCore.QRect(590, 190, 100, 25))
        self.key9Lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.key9Lbl.setObjectName("key9Lbl")
        self.resetBttn = QtWidgets.QPushButton(SortedKeys)
        self.resetBttn.setGeometry(QtCore.QRect(330, 260, 150, 50))
        self.resetBttn.setObjectName("resetBttn")

        self.retranslateUi(SortedKeys)
        QtCore.QMetaObject.connectSlotsByName(SortedKeys)

    def retranslateUi(self, SortedKeys):
        _translate = QtCore.QCoreApplication.translate
        SortedKeys.setWindowTitle(_translate("SortedKeys", "Sorted Keys"))
        self.quitBttn.setText(_translate("SortedKeys", "Quit"))
        self.acceptBttn.setText(_translate("SortedKeys", "Accept"))
        self.helpBttn.setText(_translate("SortedKeys", "Help"))
        self.titleLbl.setText(_translate("SortedKeys", "Select Sort Keys"))
        self.key1Lbl.setText(_translate("SortedKeys", "Key 1"))
        self.key2Lbl.setText(_translate("SortedKeys", "Key 2"))
        self.key3Lbl.setText(_translate("SortedKeys", "Key 3"))
        self.key4Lbl.setText(_translate("SortedKeys", "Key 4"))
        self.key5Lbl.setText(_translate("SortedKeys", "Key 5"))
        self.key6Lbl.setText(_translate("SortedKeys", "Key 6"))
        self.key7Lbl.setText(_translate("SortedKeys", "Key 7"))
        self.key8Lbl.setText(_translate("SortedKeys", "Key 8"))
        self.key9Lbl.setText(_translate("SortedKeys", "Key 9"))
        self.resetBttn.setText(_translate("SortedKeys", "Reset"))

