# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifiles/verbconjugation.ui'
#
# Created: Thu Jan 25 11:35:23 2018
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VerbConjugation(object):
    def setupUi(self, VerbConjugation):
        VerbConjugation.setObjectName("VerbConjugation")
        VerbConjugation.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(16)
        VerbConjugation.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../usr/share/machinetrans/resources/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VerbConjugation.setWindowIcon(icon)
        self.titleLbl = QtWidgets.QLabel(VerbConjugation)
        self.titleLbl.setGeometry(QtCore.QRect(10, 10, 780, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLbl.setFont(font)
        self.titleLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.firstLbl = QtWidgets.QLabel(VerbConjugation)
        self.firstLbl.setGeometry(QtCore.QRect(50, 80, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.firstLbl.setFont(font)
        self.firstLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.firstLbl.setObjectName("firstLbl")
        self.secondLbl = QtWidgets.QLabel(VerbConjugation)
        self.secondLbl.setGeometry(QtCore.QRect(420, 80, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.secondLbl.setFont(font)
        self.secondLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.secondLbl.setObjectName("secondLbl")
        self.thirdLbl = QtWidgets.QLabel(VerbConjugation)
        self.thirdLbl.setGeometry(QtCore.QRect(50, 130, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.thirdLbl.setFont(font)
        self.thirdLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.thirdLbl.setObjectName("thirdLbl")
        self.firstpLbl = QtWidgets.QLabel(VerbConjugation)
        self.firstpLbl.setGeometry(QtCore.QRect(420, 130, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.firstpLbl.setFont(font)
        self.firstpLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.firstpLbl.setObjectName("firstpLbl")
        self.thirdpLbl = QtWidgets.QLabel(VerbConjugation)
        self.thirdpLbl.setGeometry(QtCore.QRect(50, 180, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.thirdpLbl.setFont(font)
        self.thirdpLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.thirdpLbl.setObjectName("thirdpLbl")
        self.cancelBttn = QtWidgets.QPushButton(VerbConjugation)
        self.cancelBttn.setGeometry(QtCore.QRect(90, 530, 150, 50))
        self.cancelBttn.setObjectName("cancelBttn")
        self.acceptBttn = QtWidgets.QPushButton(VerbConjugation)
        self.acceptBttn.setGeometry(QtCore.QRect(560, 530, 150, 50))
        self.acceptBttn.setObjectName("acceptBttn")
        self.thirdpEditru = LineEditRU(VerbConjugation)
        self.thirdpEditru.setGeometry(QtCore.QRect(420, 490, 330, 30))
        self.thirdpEditru.setText("")
        self.thirdpEditru.setAlignment(QtCore.Qt.AlignCenter)
        self.thirdpEditru.setObjectName("thirdpEditru")
        self.secondLblru = QtWidgets.QLabel(VerbConjugation)
        self.secondLblru.setGeometry(QtCore.QRect(420, 370, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.secondLblru.setFont(font)
        self.secondLblru.setAlignment(QtCore.Qt.AlignCenter)
        self.secondLblru.setObjectName("secondLblru")
        self.thirdpLblru = QtWidgets.QLabel(VerbConjugation)
        self.thirdpLblru.setGeometry(QtCore.QRect(420, 470, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.thirdpLblru.setFont(font)
        self.thirdpLblru.setAlignment(QtCore.Qt.AlignCenter)
        self.thirdpLblru.setObjectName("thirdpLblru")
        self.firstLblru = QtWidgets.QLabel(VerbConjugation)
        self.firstLblru.setGeometry(QtCore.QRect(50, 370, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.firstLblru.setFont(font)
        self.firstLblru.setAlignment(QtCore.Qt.AlignCenter)
        self.firstLblru.setObjectName("firstLblru")
        self.thirdLblru = QtWidgets.QLabel(VerbConjugation)
        self.thirdLblru.setGeometry(QtCore.QRect(50, 420, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.thirdLblru.setFont(font)
        self.thirdLblru.setAlignment(QtCore.Qt.AlignCenter)
        self.thirdLblru.setObjectName("thirdLblru")
        self.firstpLblru = QtWidgets.QLabel(VerbConjugation)
        self.firstpLblru.setGeometry(QtCore.QRect(420, 420, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.firstpLblru.setFont(font)
        self.firstpLblru.setAlignment(QtCore.Qt.AlignCenter)
        self.firstpLblru.setObjectName("firstpLblru")
        self.secondEditru = LineEditRU(VerbConjugation)
        self.secondEditru.setGeometry(QtCore.QRect(420, 390, 330, 30))
        self.secondEditru.setAlignment(QtCore.Qt.AlignCenter)
        self.secondEditru.setObjectName("secondEditru")
        self.firstpEditru = LineEditRU(VerbConjugation)
        self.firstpEditru.setGeometry(QtCore.QRect(420, 440, 330, 30))
        self.firstpEditru.setText("")
        self.firstpEditru.setAlignment(QtCore.Qt.AlignCenter)
        self.firstpEditru.setObjectName("firstpEditru")
        self.thirdEditru = LineEditRU(VerbConjugation)
        self.thirdEditru.setGeometry(QtCore.QRect(50, 440, 330, 30))
        self.thirdEditru.setText("")
        self.thirdEditru.setAlignment(QtCore.Qt.AlignCenter)
        self.thirdEditru.setObjectName("thirdEditru")
        self.firstEditru = LineEditRU(VerbConjugation)
        self.firstEditru.setGeometry(QtCore.QRect(50, 390, 330, 30))
        self.firstEditru.setAlignment(QtCore.Qt.AlignCenter)
        self.firstEditru.setObjectName("firstEditru")
        self.titleLblru = QtWidgets.QLabel(VerbConjugation)
        self.titleLblru.setGeometry(QtCore.QRect(0, 240, 780, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.titleLblru.setFont(font)
        self.titleLblru.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLblru.setObjectName("titleLblru")
        self.secondpLblru = QtWidgets.QLabel(VerbConjugation)
        self.secondpLblru.setGeometry(QtCore.QRect(50, 470, 330, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.secondpLblru.setFont(font)
        self.secondpLblru.setAlignment(QtCore.Qt.AlignCenter)
        self.secondpLblru.setObjectName("secondpLblru")
        self.secondpEditru = LineEditRU(VerbConjugation)
        self.secondpEditru.setGeometry(QtCore.QRect(50, 490, 330, 30))
        self.secondpEditru.setText("")
        self.secondpEditru.setAlignment(QtCore.Qt.AlignCenter)
        self.secondpEditru.setObjectName("secondpEditru")
        self.conjBttn = QtWidgets.QPushButton(VerbConjugation)
        self.conjBttn.setGeometry(QtCore.QRect(300, 530, 180, 50))
        self.conjBttn.setObjectName("conjBttn")
        self.stemLbl = QtWidgets.QLabel(VerbConjugation)
        self.stemLbl.setGeometry(QtCore.QRect(120, 340, 200, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.stemLbl.setFont(font)
        self.stemLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.stemLbl.setObjectName("stemLbl")
        self.stemEdit = LineEditRU(VerbConjugation)
        self.stemEdit.setGeometry(QtCore.QRect(350, 340, 330, 30))
        self.stemEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.stemEdit.setObjectName("stemEdit")
        self.caseLbl = QtWidgets.QLabel(VerbConjugation)
        self.caseLbl.setGeometry(QtCore.QRect(120, 310, 200, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.caseLbl.setFont(font)
        self.caseLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.caseLbl.setObjectName("caseLbl")
        self.caseBox = QtWidgets.QComboBox(VerbConjugation)
        self.caseBox.setGeometry(QtCore.QRect(350, 310, 330, 34))
        self.caseBox.setObjectName("caseBox")
        self.helpBttn = QtWidgets.QPushButton(VerbConjugation)
        self.helpBttn.setGeometry(QtCore.QRect(640, 0, 150, 50))
        self.helpBttn.setObjectName("helpBttn")
        self.firstEdit = LineEditEN(VerbConjugation)
        self.firstEdit.setGeometry(QtCore.QRect(50, 100, 330, 30))
        self.firstEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.firstEdit.setObjectName("firstEdit")
        self.secondEdit = LineEditEN(VerbConjugation)
        self.secondEdit.setGeometry(QtCore.QRect(410, 100, 330, 30))
        self.secondEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.secondEdit.setObjectName("secondEdit")
        self.thirdEdit = LineEditEN(VerbConjugation)
        self.thirdEdit.setGeometry(QtCore.QRect(50, 150, 330, 30))
        self.thirdEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.thirdEdit.setObjectName("thirdEdit")
        self.firstpEdit = LineEditEN(VerbConjugation)
        self.firstpEdit.setGeometry(QtCore.QRect(410, 150, 330, 30))
        self.firstpEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.firstpEdit.setObjectName("firstpEdit")
        self.thirdpEdit = LineEditEN(VerbConjugation)
        self.thirdpEdit.setGeometry(QtCore.QRect(50, 200, 330, 30))
        self.thirdpEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.thirdpEdit.setObjectName("thirdpEdit")
        self.ruVerbEdit = LineEditRU(VerbConjugation)
        self.ruVerbEdit.setGeometry(QtCore.QRect(350, 280, 330, 30))
        self.ruVerbEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ruVerbEdit.setObjectName("ruVerbEdit")
        self.ruVerbLbl = QtWidgets.QLabel(VerbConjugation)
        self.ruVerbLbl.setGeometry(QtCore.QRect(120, 280, 200, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ruVerbLbl.setFont(font)
        self.ruVerbLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.ruVerbLbl.setObjectName("ruVerbLbl")
        self.enVerbLbl = QtWidgets.QLabel(VerbConjugation)
        self.enVerbLbl.setGeometry(QtCore.QRect(200, 50, 170, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enVerbLbl.setFont(font)
        self.enVerbLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.enVerbLbl.setObjectName("enVerbLbl")
        self.enVerbEdit = LineEditEN(VerbConjugation)
        self.enVerbEdit.setGeometry(QtCore.QRect(410, 50, 330, 30))
        self.enVerbEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.enVerbEdit.setObjectName("enVerbEdit")
        self.recBttn = QtWidgets.QPushButton(VerbConjugation)
        self.recBttn.setGeometry(QtCore.QRect(630, 190, 150, 50))
        self.recBttn.setObjectName("recBttn")
        self.recLbl = QtWidgets.QLabel(VerbConjugation)
        self.recLbl.setGeometry(QtCore.QRect(420, 190, 200, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.recLbl.setFont(font)
        self.recLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.recLbl.setObjectName("recLbl")
        self.selfCheck = QtWidgets.QCheckBox(VerbConjugation)
        self.selfCheck.setGeometry(QtCore.QRect(50, 50, 130, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.selfCheck.setFont(font)
        self.selfCheck.setObjectName("selfCheck")

        self.retranslateUi(VerbConjugation)
        QtCore.QMetaObject.connectSlotsByName(VerbConjugation)
        VerbConjugation.setTabOrder(self.helpBttn, self.selfCheck)
        VerbConjugation.setTabOrder(self.selfCheck, self.enVerbEdit)
        VerbConjugation.setTabOrder(self.enVerbEdit, self.firstEdit)
        VerbConjugation.setTabOrder(self.firstEdit, self.secondEdit)
        VerbConjugation.setTabOrder(self.secondEdit, self.thirdEdit)
        VerbConjugation.setTabOrder(self.thirdEdit, self.firstpEdit)
        VerbConjugation.setTabOrder(self.firstpEdit, self.thirdpEdit)
        VerbConjugation.setTabOrder(self.thirdpEdit, self.recBttn)
        VerbConjugation.setTabOrder(self.recBttn, self.ruVerbEdit)
        VerbConjugation.setTabOrder(self.ruVerbEdit, self.caseBox)
        VerbConjugation.setTabOrder(self.caseBox, self.stemEdit)
        VerbConjugation.setTabOrder(self.stemEdit, self.firstEditru)
        VerbConjugation.setTabOrder(self.firstEditru, self.secondEditru)
        VerbConjugation.setTabOrder(self.secondEditru, self.thirdEditru)
        VerbConjugation.setTabOrder(self.thirdEditru, self.firstpEditru)
        VerbConjugation.setTabOrder(self.firstpEditru, self.secondpEditru)
        VerbConjugation.setTabOrder(self.secondpEditru, self.thirdpEditru)
        VerbConjugation.setTabOrder(self.thirdpEditru, self.cancelBttn)
        VerbConjugation.setTabOrder(self.cancelBttn, self.conjBttn)
        VerbConjugation.setTabOrder(self.conjBttn, self.acceptBttn)

    def retranslateUi(self, VerbConjugation):
        _translate = QtCore.QCoreApplication.translate
        VerbConjugation.setWindowTitle(_translate("VerbConjugation", "Verb Conjugation"))
        self.titleLbl.setText(_translate("VerbConjugation", "English Verb Conjugation for "))
        self.firstLbl.setText(_translate("VerbConjugation", "First Person -- I"))
        self.secondLbl.setText(_translate("VerbConjugation", "Second Person -- You"))
        self.thirdLbl.setText(_translate("VerbConjugation", "Third Person -- He She It"))
        self.firstpLbl.setText(_translate("VerbConjugation", "First Person Plural -- We"))
        self.thirdpLbl.setText(_translate("VerbConjugation", "Third Person Plural -- They"))
        self.cancelBttn.setText(_translate("VerbConjugation", "Cancel"))
        self.acceptBttn.setText(_translate("VerbConjugation", "Accept"))
        self.secondLblru.setText(_translate("VerbConjugation", "Second Person -- Ты"))
        self.thirdpLblru.setText(_translate("VerbConjugation", "Third Person Plural -- Они"))
        self.firstLblru.setText(_translate("VerbConjugation", "First Person -- Я"))
        self.thirdLblru.setText(_translate("VerbConjugation", "Third Person -- Он Она Оно"))
        self.firstpLblru.setText(_translate("VerbConjugation", "First Person Plural -- Мы"))
        self.titleLblru.setText(_translate("VerbConjugation", "Russian Verb Conjugation for "))
        self.secondpLblru.setText(_translate("VerbConjugation", "Second Person Plural -- Вы"))
        self.conjBttn.setText(_translate("VerbConjugation", "Conjugations"))
        self.stemLbl.setText(_translate("VerbConjugation", "Verb Stem"))
        self.caseLbl.setText(_translate("VerbConjugation", "Verb Case"))
        self.helpBttn.setText(_translate("VerbConjugation", "Help"))
        self.ruVerbLbl.setText(_translate("VerbConjugation", "Russian Verb"))
        self.enVerbLbl.setText(_translate("VerbConjugation", "English Verb"))
        self.recBttn.setText(_translate("VerbConjugation", "Recalculate"))
        self.recLbl.setText(_translate("VerbConjugation", "<html><head/><body>Erases all saved<br>verbal values</body></html>"))
        self.selfCheck.setText(_translate("VerbConjugation", "Oneself"))

from machinetrans.lineeditru import LineEditRU
from machinetrans.lineediten import LineEditEN
